In [2]:
import json
import pandas as pd
from scipy.stats import pearsonr, spearmanr
import matplotlib.pyplot as plt

In [4]:
with open(r"D:\finding jobs notes and usc things\USC projects\FORTIS LAB\AIEDUReportPlace\0908\result\llama_scores.json", "r", encoding="utf-8") as f:
    llama_data = json.load(f)
with open(r"D:\finding jobs notes and usc things\USC projects\FORTIS LAB\AIEDUReportPlace\0908\result\mistral_score.json", "r", encoding="utf-8") as f:
    mistral_data = json.load(f)
with open(r"D:\finding jobs notes and usc things\USC projects\FORTIS LAB\AIEDUReportPlace\0908\result\MRBench_V1_score_result.json", "r", encoding="utf-8") as f:
    mrbench_data = json.load(f)

In [16]:
df_llama = pd.DataFrame([
    {"conversation_history": d.get("conversation_history") or d.get("conversation_histroy"),
     "llama_score_df": d["points"] if "points" in d else d.get("llama_score")}
    for d in llama_data
])

df_mistral = pd.DataFrame([
    {"conversation_history": d.get("conversation_history") or d.get("conversation_histroy"),
     "mistral_score_df": d["points"] if "points" in d else d.get("mistral_score")}
    for d in mistral_data
])

df_mrbench = pd.DataFrame([
    {"conversation_history": d["conversation_history"],
     "llama_score_mr": d["llama_score"],
     "mistral_score_mr": d["mistral_score"]}
    for d in mrbench_data
])

In [22]:
df_mrbenchdf = df_mrbench.merge(df_llama, on="conversation_history").merge(df_mistral, on="conversation_history")
df_mrbenchdf

,conversation_history,llama_score_mr,mistral_score_mr,llama_score_df,mistral_score_df
0,"Tutor: Hi, could you please provide a step-by-...","[1, 1, 3, 1, 1, 1, 1, 1]","[1, 1, 3, 1, 1, 1, 1, 1]","[3, 3, 3, 2, 1, 1, 1, 2]","[3, 3, 3, 2, 1, 1, 1, 2]"
1,"Tutor: Hi, could you please provide a step-by-...","[3, 3, 3, 2, 3, 1, 2, 2]","[3, 3, 3, 2, 3, 1, 2, 2]","[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
2,"Tutor: Examples: triangles, rectangles and pen...","[1, 1, 1, 3, 3, 1, 1, 2]","[1, 1, 1, 3, 3, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1]"
3,"Tutor: Hi, could you please provide a step-by-...","[1, 3, 3, 2, 1, 1, 1, 2]","[1, 3, 3, 2, 1, 1, 1, 2]","[3, 3, 1, 1, 2, 1, 1, 1]","[3, 3, 1, 1, 2, 1, 1, 1]"
4,Tutor: A quadrilateral is a shape with four si...,"[1, 1, 1, 1, 3, 1, 1, 2]","[1, 1, 1, 1, 3, 1, 1, 2]","[3, 3, 3, 2, 1, 1, 1, 2]","[3, 3, 3, 2, 1, 1, 1, 2]"
...,...,...,...,...,...
185,"Tutor: Hi, could you please provide a step-by-...","[1, 2, 3, 2, 1, 1, 1, 2]","[1, 2, 3, 2, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
186,"Tutor: Hi, could you please provide a step-by-...","[1, 1, 3, 3, 3, 1, 1, 2]","[1, 1, 3, 3, 3, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
187,"Tutor: Hi, could you please provide a step-by-...","[3, 3, 3, 2, 1, 1, 1, 2]","[3, 3, 3, 2, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
188,"Tutor: Hi, could you please provide a step-by-...","[1, 1, 3, 1, 1, 1, 1, 2]","[1, 1, 3, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1]"
189,"Tutor: Hi, could you please provide a step-by-...","[1, 1, 3, 1, 1, 1, 1, 2]","[1, 1, 3, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"

In [29]:
from scipy.stats import pearsonr, spearmanr
import pandas as pd

results = []

# 逐個維度（例如一共有 8 個維度）計算
n_dim = 8
df = df_mrbenchdf
for i in range(n_dim):
    # 取出這個維度的分數
    llama_mr = [x[i] for x in df["llama_score_mr"]]
    llama_df = [x[i] for x in df["llama_score_df"]]
    mistral_mr = [x[i] for x in df["mistral_score_mr"]]
    mistral_df = [x[i] for x in df["mistral_score_df"]]

    results.append({
        "dimension": i,
        "pearson_llama": pearsonr(llama_mr, llama_df)[0],
        "spearman_llama": spearmanr(llama_mr, llama_df)[0],
        "pearson_mistral": pearsonr(mistral_mr, mistral_df)[0],
        "spearman_mistral": spearmanr(mistral_mr, mistral_df)[0],
    })

results_df = pd.DataFrame(results)
print(results_df)

   dimension  pearson_llama  spearman_llama  pearson_mistral  spearman_mistral
0          0       0.042480        0.044360         0.042480          0.044360
1          1       0.048023        0.044396         0.048023          0.044396
2          2       0.016983        0.023928         0.016983          0.023928
3          3      -0.074892       -0.090202        -0.074892         -0.090202
4          4      -0.102909       -0.121731        -0.102909         -0.121731
5          5      -0.013135       -0.013135        -0.013135         -0.013135
6          6      -0.040866       -0.043639        -0.040866         -0.043639
7          7      -0.031799       -0.031799        -0.031799         -0.031799

In [15]:
# 取出三個 dataframe 的 conversation_history
set_llama = set(df_llama["conversation_history"])
set_mistral = set(df_mistral["conversation_history"])
set_mrbench = set(df_mrbench["conversation_history"])

# 找出不一樣的地方
only_in_llama = set_llama - set_mistral - set_mrbench
only_in_mistral = set_mistral - set_llama - set_mrbench
only_in_mrbench = set_mrbench - set_llama - set_mistral

# 交集（大家都有的）
common = set_llama & set_mistral & set_mrbench

print("✅ 三者都有的數量:", len(common))
print("⚠️ 只在 LLaMA 有的:", len(only_in_llama))
print("⚠️ 只在 Mistral 有的:", len(only_in_mistral))
print("⚠️ 只在 MRBench 有的:", len(only_in_mrbench))

✅ 三者都有的數量: 169
⚠️ 只在 LLaMA 有的: 0
⚠️ 只在 Mistral 有的: 0
⚠️ 只在 MRBench 有的: 19

In [ ]:
df = df_mrbench.merge(df_llama, on="conversation_history").merge(df_mistral, on="conversation_history")

,conversation_history,mrbench,llama_score,mistral_score
0,"Tutor: Hi, could you please provide a step-by-...",None,"[3, 3, 3, 2, 1, 1, 1, 2]","[3, 3, 3, 2, 1, 1, 1, 2]"
1,"Tutor: Hi, could you please provide a step-by-...",None,"[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
2,"Tutor: Examples: triangles, rectangles and pen...",None,"[1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1]"
3,"Tutor: Hi, could you please provide a step-by-...",None,"[3, 3, 1, 1, 2, 1, 1, 1]","[3, 3, 1, 1, 2, 1, 1, 1]"
4,Tutor: A quadrilateral is a shape with four si...,None,"[3, 3, 3, 2, 1, 1, 1, 2]","[3, 3, 3, 2, 1, 1, 1, 2]"
...,...,...,...,...
185,"Tutor: Hi, could you please provide a step-by-...",None,"[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
186,"Tutor: Hi, could you please provide a step-by-...",None,"[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
187,"Tutor: Hi, could you please provide a step-by-...",None,"[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"
188,"Tutor: Hi, could you please provide a step-by-...",None,"[1, 1, 1, 1, 1, 1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1]"
189,"Tutor: Hi, could you please provide a step-by-...",None,"[1, 1, 1, 1, 1, 1, 1, 2]","[1, 1, 1, 1, 1, 1, 1, 2]"

                                  conversation_history mrbench
0    Tutor: Hi, could you please provide a step-by-...    None
1    Tutor: Hi, could you please provide a step-by-...    None
2    Tutor: Examples: triangles, rectangles and pen...    None
3    Tutor: Hi, could you please provide a step-by-...    None
4    Tutor: Hi, could you please provide a step-by-...    None
..                                                 ...     ...
187  Tutor: Hi, could you please provide a step-by-...    None
188  Tutor: Hi, could you please provide a step-by-...    None
189  Tutor: Hi, could you please provide a step-by-...    None
190  Tutor: Hi, could you please provide a step-by-...    None
191  Tutor: Hi, could you please provide a step-by-...    None

[192 rows x 2 columns]